

Insert into products(ID,BRAND, COLOR,DESCRIPTION,NAME, PRODUCT_TYPE,QUANTITY_PER_UNIT,SIZE,SUPPLIER_ID,UNIT_PRICE,UNITs_IN_STOCK)
VALUES('123', 'LEVIS', 'RED','shirt','shirt','CLOTH',20,'10','124',120,120);
Insert into products(ID,BRAND, COLOR,DESCRIPTION,NAME, PRODUCT_TYPE,QUANTITY_PER_UNIT,SIZE,SUPPLIER_ID,UNIT_PRICE,UNITs_IN_STOCK)
VALUES('124', 'LEVIS', 'RED','paint','paint','CLOTH',20,'10','124',120,120);
Insert into products(ID,BRAND, COLOR,DESCRIPTION,NAME, PRODUCT_TYPE,QUANTITY_PER_UNIT,SIZE,SUPPLIER_ID,UNIT_PRICE,UNITs_IN_STOCK)
VALUES('125', 'PUMA', 'RED','shoes','shoes','Footwear',20,'10','124',120,120);
Insert into products(ID,BRAND, COLOR,DESCRIPTION,NAME, PRODUCT_TYPE,QUANTITY_PER_UNIT,SIZE,SUPPLIER_ID,UNIT_PRICE,UNITs_IN_STOCK)
VALUES('126', 'adidas', 'white','shoes','shoes','Footwear',20,'10','124',120,120);
Insert into products(ID,BRAND, COLOR,DESCRIPTION,NAME, PRODUCT_TYPE,QUANTITY_PER_UNIT,SIZE,SUPPLIER_ID,UNIT_PRICE,UNITs_IN_STOCK)
VALUES('127', 'Flying', 'blue','shirt','shirt','CLOTH',20,'10','124',120,120);
commit;