

Insert into products(ID,BRAND, COLOR,DESCRIPTION,NAME, PRODUCT_TYPE,QUANTITY_PER_UNIT,SIZE,SUPPLIER_ID,UNIT_PRICE,UNITs_IN_STOCK)
VALUES('123', 'LEVIS', 'RED','SHIRT','SHIRT','CLOTH','20','10','124',120,120);
Insert into products(ID,BRAND, COLOR,DESCRIPTION,NAME, PRODUCT_TYPE,QUANTITY_PER_UNIT,SIZE,SUPPLIER_ID,UNIT_PRICE,UNITs_IN_STOCK)
VALUES('124', 'LEVIS', 'RED','Paint','SHIRT','CLOTH','20','10','124',120,120);
commit;